---
- hosts: localhost
  name: Create infrastructure with Terraforms
  vars:
    terraform_dir: /Users/adam.toy/TerraformProjects/terraform_proxmox 
 
  tasks:
    - name: Terraform Apply
      terraform:
        project_path: "{{ terraform_dir }}"
        variables_files: "live.tfvars"
        state: present
      register: outputs

    - name: debug
      debug:
        msg: "{{ outputs }}"
 
    - name: Create Init Master Group
      add_host: 
        name: "{{ outputs.outputs.init_master_address.value }}"
        groups: init_master

    - name: Create Additional Master Group
      add_host: 
        name: "{{ item }}"
        groups: additional_masters
      with_items: "{{ outputs.outputs.additional_master_addresses.value }}"

    - name: Create Worker Group
      add_host: 
        name: "{{ item }}"
        groups: workers
      with_items: "{{ outputs.outputs.worker_addresses.value }}"

    - name: debug
      debug:
        msg: "{{ groups }}"

- hosts: init_master
  name: Install RKE2 (Init Master)
  become: yes
  gather_facts: false
 
  pre_tasks:
    - name: Testing Connection 
      wait_for_connection:
        delay: 20
        timeout: 60

    - name: Testing
      debug:
        msg: "{{ init_master }}"

    - debug:
        var=hostvars[inventory_hostname]

  roles: 
    - rke2

- hosts: additional_masters
  name: Install RKE2 (Additional Masters)
  serial: 1
  become: yes
  gather_facts: false
 
  pre_tasks:
    - name: Testing Connection 
      wait_for_connection:
        delay: 20
        timeout: 60
      when: "'localhost' not in inventory_hostname"

    - debug:
        var=hostvars[inventory_hostname]

  roles: 
    - rke2

- hosts: workers
  name: Install RKE2 (Workers)
  become: yes
  gather_facts: false
 
  pre_tasks:
    - name: Testing Connection 
      wait_for_connection:
        delay: 20
        timeout: 60
      when: "'localhost' not in inventory_hostname"

    - debug:
        var=hostvars[inventory_hostname]

  roles: 
    - rke2