---
- name: Install curl
  yum:
    name: curl
    state: latest
    update_cache: true

- name: Download kubectl
  args:
    warn: false
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin