---

- import_tasks: yum.yml
  when: "'localhost' not in inventory_hostname"

- import_tasks: master-config.yml
  when: "'init_master' in group_names or 'additional_masters' in group_names"

- import_tasks: agent-config.yml
  when: "'workers' in group_names"

# Firewalld | disable
- name: FIREWALLD | disable
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: "'localhost' not in inventory_hostname"

# CIS mode
- import_tasks: cis-profile.yml
  when: rke2_cis_mode
  when: "'localhost' not in inventory_hostname"

#need to add when role==master
- import_tasks: rke2-master.yml
  when: "'init_master' in group_names or 'additional_masters' in group_names"

- import_tasks: rke2-master-additions.yml
  when: "'init_master' in group_names or 'additional_masters' in group_names"

- import_tasks: rke2-agent.yml
  when: "'workers' in group_names"

- import_tasks: kubectl-install.yml
  when: "'init_master' in group_names or 'additional_masters' in group_names"

- import_tasks: kubectl-config.yml
  when: "'init_master' in group_names or 'additional_masters' in group_names"
