---
# /etc/rancher/rke2/config.yaml`
- name: create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: create the airgap images folder
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/agent/images
    state: directory
    recurse: yes

    
- name: Create Init Master Config File 
  ansible.builtin.template:
    src: ../templates/init_master_config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0600
  when: "'init_master' in group_names"

- name: Create Additional Master Config File 
  ansible.builtin.template:
    src: ../templates/master_config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0600
  when: "'additional_masters' in group_names"

